using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

public class ModSfx : MonoBehaviour
{
    public int MaxModeSfx;
    public List<ModClips> modsSfx;

    [Serializable]
    public class ModClips {
        public AudioClip[] clips;
        public AnimationsManager.anim animName;
    }

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public AudioClip GetModClip(AnimationsManager.anim animName, int index) {
        ModClips mc = modsSfx.Find(x => x.animName == animName);
        return mc.clips[index];
    }

    public bool Contains(AnimationsManager.anim animName) {
       return modsSfx.Find(x => x.animName == animName)!=null;
    }
}
